length = input('Enter the length of the rectangle in meters: ')
length = float(length)
width = input('Enter the width of the rectangle in meters: ')
width = float(width)
perimeter = ((length+width)*2)
ppm = input('Enter the price per meter of fencing: ')
ppm = float(ppm)
a = (perimeter*ppm)
print('The total cost is: '+str(a)+'euros')